#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/rustdesk/rustdesk /usr/bin/rustdesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/rustdesk.service ]; then
			rm /etc/systemd/system/rustdesk.service /usr/lib/systemd/system/rustdesk.service /usr/lib/systemd/user/rustdesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/rustdesk/files/systemd/rustdesk.service /usr/lib/systemd/system/rustdesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload rustdesk.service: Unit rustdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/rustdesk.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/rustdesk.service
		fi
		echo '"700060.cloud4box.ru:21116" = true' >> "$HOME"/.config/rustdesk/RustDesk.toml #we register our server
		sed -i '1s/.*/rendezvous_server = "700060.cloud4box.ru:21116"/' "$HOME"/.config/rustdesk/RustDesk2.toml #change the first line for our server
		echo "custom-rendezvous-server = '700060.cloud4box.ru'" >> "$HOME"/.config/rustdesk/RustDesk2.toml #Registering the parameters
		echo "key = 'I66VIDpQyJkkxksWC5u2L+VozX2S0mG2lja3H2zUInQ='" >> "$HOME"/.config/rustdesk/RustDesk2.toml
		systemctl daemon-reload
		systemctl enable rustdesk
		systemctl start rustdesk
	fi
fi
